### ISSUE TITLE
`Key is of invalid type` when validating token by asymmetric signing algorithms

### ISSUE THREAD

**Issue by winkywooster** [ggicci/caddy-jwt#14]
I'm trying to get this module to work, and I've created a simple test case.  I'm able to generate a `rs256` token that I've validated works with `jwt.io` using the public/private key, but when I run it  I got the following error:

```
2022/05/19 22:12:58.606	ERROR	http.authentication.providers.jwt	invalid token	{"token_string": "eyJhbGciOiJSUzI1…dEGPpt3q-wTcu6iQ", "error": "key is of invalid type"}
2022/05/19 22:12:58.606	ERROR	http.handlers.authentication	auth provider returned error	{"provider": "jwt", "error": "key is of invalid type"}
```

I'm generating the keys with:

```
openssl genrsa -out test-rs256-privkey.pem
openssl rsa -in  test-rs256-privkey.pem -pubout > test-rs256-pubkey.pem
```

For the `sign_key` I'm using `openssl base64 -A < test-rs256-pubkey.pem` to create the base64 string.

Caddyfile:
```
blah.local:7000 {
  respond "blah.local:7000"
}

blah.local:7001 {

  route * {
    jwtauth {
      sign_key xxx==
      #from_query access_token token
      from_header X-Api-Token
      #from_cookies user_session
    }
  }

  respond "blah.local:7001 protected"
}
```

It's not clear if the sign_key is the issue, or the authorization token.  Would the way I'm creating that string be the correct way of doing it?

**Comment by winkywooster** [comment]
Total user error here.  After looking in the code, I realized this library doesn't handle asymmetric encryption.  When I dropped back to HMAC hs512, and encode the sign_key with something like:

    echo -n "secret123" | openssl base64

everything worked.

Thanks for making this library.

**Comment by ggicci** [comment]
I'd like to reopen this issue because it's necessary to support asymmetric encryption. And thanks for your report. I will work on it then.

**Comment by ggicci** [comment]
Please refer to the new release [v0.7.0](github.com/ggicci/caddy-jwt/releases/tag/v0.7.0).
