### ISSUE TITLE
Feature Request: Support nested claim path

### ISSUE THREAD

**Issue by bandirsen** [ggicci/caddy-jwt#2]
Current implementation can only get non standard jwt claim value from top level, for example
```
{
    "sub": "1234",
    "iss": "http://myissuer.com",
    "aud": "myaudience",
   ... other standard jwt claims
  
   "role": "role"
}
```
we can get ```role``` claim without problem with adding  ```meta_claims "role"``` to configuration

However sometimes custom jwt claim is in nested format, for example : 
```
{
    "sub": "1234",
    "iss": "http://myissuer.com",
    "aud": "myaudience",
   ... other standard jwt claims
  
   "user_info": {
       "role": "admin",      
   }
}
```

Maybe we can use dot separated path, to track claim we need.
For example to get role claim from above example, we can write this in configuration :
``` meta_claims "user_info.role -> role" ```

**Comment by ggicci** [comment]
Sounds reasonable and useful. I will work on it soon. Thanks for the suggestion to improve this module.
