### ISSUE TITLE
JWK Support

### ISSUE THREAD

**Issue by davidpanic** [ggicci/caddy-jwt#27]
I would like to see JWK support added to this module. That would allow people to use rolling keys, like firebase does. The relevant RFC is [7517](https://www.rfc-editor.org/rfc/rfc7517). The firebase JWK endpoint is located at https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com

**Comment by ggicci** [comment]
Hi @davidpanic , thanks for the feedback and sorry for the late response. After reading the RFC roughly, I had the following questions if you could help:

1. To my understanding, JWK is just a data structure. As for the support of rolling keys, it should be a standalone mechanism implemented. Did you mean you need an automated key generation&rolling feature in `caddy-jwt`? 
2. If it's an YES to the above question, did you expect to expose an endpoint to get the keys just like firebase does?

**Comment by davidpanic** [comment]
The feature I need is not for caddy to expose that endpoint, but to be able to authenticate against it.

The way it's supposed to work is that the server exposes a "JWKs" endpoint like the firebase one above. The HTTP response may or may not include Cache-Control or Expires headers that tell the clients when to refresh the keys from the API.

**Comment by davidpanic** [comment]
An example of a good implementation for JWK support is in my opinion Hasura, take a look at the documentation here: https://hasura.io/docs/latest/auth/authentication/jwt/#configuring-jwt-mode

**Comment by ggicci** [comment]
hi @davidpanic I've published a new release v0.8.0 which supports JWK. Please have a look at the implementation to see if it works as intended. And feel free to raise questions here. I will keep it updated.

**Comment by davidpanic** [comment]
As far as I can tell this works beautifully, I have not tested cache expiry but I believe it to be implemented correctly. Thank you for this quick implementation!
