### ISSUE TITLE
Improve error message on missing kid header

### ISSUE THREAD

**Issue by 1-alex98** [ggicci/caddy-jwt#41]
if you use jwk url and do not have a kid in the jwt token header you will get the following error message:
`caddy-caddy-1  | {"level":"error","ts":1683200873.3749237,"logger":"http.handlers.authentication","msg":"auth provider returned error","provider":"jwt","error":"key provider 0 failed: key not found: "}
`
Took me quite some time to understand what was going on.
https://github.com/ggicci/caddy-jwt/blob/2e859ac18f792013680bf6dcfb84c095dee14ada/jwt.go#L213
I would suggest:
```
if kid is empty or nil {
 return fmt.Errorf("JWT key needs a header called kid matching the key id");
}
```
or change implementation to go through all keys instead of relying on the optional kid header to match the jwk.

Nice Module thx a lot.

**Comment by ggicci** [comment]
Thanks for the report. I'm looking into this.
