### ISSUE TITLE
if enable jwtauth ，then caddy cannot start .

### ISSUE THREAD

**Issue by zuohuadong** [ggicci/caddy-jwt#42]
```
host.xxx  {
      reverse_proxy  http://wapi.xxx
      jwtauth {
          sign_key 5bsddsdsd
          sign_alg HS256
          from_query access_token token
          from_header authorization
      }
}
```

directive 'jwtauth' is not an ordered HTTP handler, so it cannot  be used here.

or 
```
{
	order jwtauth before basicauth
}
host.xxx  {
      reverse_proxy  http://wapi.xxx
      jwtauth {
          sign_key 5bsddsdsd
          sign_alg HS256
          from_query access_token token
          from_header authorization
      }
}
```

adapting config using caddyfile: server block without any key is global configuration, and if used, it must be first

```
host.xxx  {
        route {
         order jwtauth before basicauth
       }
}
```

during parsing: unrecognized directive: order - are you sure your Caddyfile structure (nesting and braces) is correct?

How to Use it?

**Comment by ggicci** [comment]
The plugin should work as expected, please take a look at [here](https://github.com/ggicci/caddy-jwt/issues/36#issuecomment-1472609064), there's a tested Caddyfile.

**Comment by zuohuadong** [comment]
@ggicci  no . Whenever I start it, I see an error. Is it because of a conflict with caddy-git?

**Comment by ggicci** [comment]
```
{
	order jwtauth before basicauth
}
host.xxx  {
      
      jwtauth {
          sign_key 5bsddsdsd
          sign_alg HS256
          from_query access_token token
          from_header authorization
      }

      reverse_proxy  http://wapi.xxx
}
```

try this?

**Comment by ggicci** [comment]
Hi @zuohuadong have you got any updates on this?

**Comment by zuohuadong** [comment]
@ggicci  Sorry to get back to you now. I think I probably know the problem.

ERROR：

```
{
	order jwtauth before basicauth
}
{
        git  {
        ......
        }
}
```

right: 
```
{
        order jwtauth before basicauth
        git  {
        ......
        }
}

```

**Comment by ggicci** [comment]
good to hear, then i'm gonna close this issue as it is related to Caddy configuration itself
