### ISSUE TITLE
JWT header's alg is not taken into consideration when using JWK URL

### ISSUE THREAD

**Issue by core2duoe6420** [ggicci/caddy-jwt#71]
Although the comment [here](https://github.com/ggicci/caddy-jwt/blob/main/jwt.go#L54-L61) states:

```
// We will try to determine the algorithm automatically from the following sources:
// 1. The "alg" field in the JWT header.
// 2. The "alg" field in the matched JWK (if JWKURL is provided).
// 3. The value set here.
SignAlgorithm string `json:"sign_alg"`
```

in `keyProvider()`, if JWK url is used, then `alg` from JWT header is not used, and if the JWK provider does not include `alg` field in the response, it will lead to an error `unsupported signature algorithm`

```
if ja.usingJWK() {
	...
	// sig.ProtectedHeaders().Algorithm() is not taken into consideration in this branch
	sink.Key(ja.determineSigningAlgorithm(key.Algorithm()), key)
} else {
	sink.Key(ja.determineSigningAlgorithm(sig.ProtectedHeaders().Algorithm()), ja.parsedSignKey)
}
```

**Comment by ggicci** [comment]
Hi @core2duoe6420 , sorry for the very late response. I was just survived from a long busy period. I hope I have understood your problem correctly. And the PR is ready now #81 . I would be appreciated if you could help review :)

**Comment by core2duoe6420** [comment]
Hi @ggicci hope all is going well for you. The PR looks good, this is exactly what I wanted to have.
