### ISSUE TITLE
jwk_url error is never logged

### ISSUE THREAD

**Issue by jchamberlain** [ggicci/caddy-jwt#79]
Thank you for this module! It seems to be exactly what I need, but I'm running into some trouble debugging why my jwk_url is not working, and unfortunately caddy-jwt doesn't tell me why. (This ticket is a request to change the logging behavior, not a request for help troubleshooting my setup.)

In `jwt.go`, in `setupJWKLoader()`, any errors from loading the URL are ignored:
```go
// ignore any error loading the JWKS endpoint now as it may not be available at startup
_ = ja.refreshJWKCache()
```

On a later refresh, errors are similarly dropped:
```go
// trigger a refresh if the key is not found
go ja.refreshJWKCache()
```

Could one or both of these be adjusted to log the error?

**Comment by ggicci** [comment]
Sure, will look into this.
